# Generated by Django 5.1.5 on 2025-01-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_remove_protocoloentrega_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocoloentrega',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
